### ISSUE TITLE
cannot install animation nodes + extra nodes

### ISSUE THREAD

**Issue by luckychris** [3DSinghVFX/animation_nodes#162]
I have no problem installing animation nodes. It just happens if i try to install animation nodes + extra nodes from here https://blender.community/c/graphicall/phbbbc/.

The error is: unsafe use of relative rpath libz.1.dylib in .....

I am using a Macbook Pro with MacOS Big Sur.
Blender 2.93 alpha (from yesterday)

**Comment by 3DSinghVFX** [comment]
Hi. Please run the Blender from the terminal and then take the screenshot of the terminal which has the complete error message.

**Comment by luckychris** [comment]
result:

Read prefs: /Users/cd/Library/Application Support/Blender/2.93/config/userpref.blend
Traceback (most recent call last):
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/ActionRecorder-master/__init__.py", line 2, in <module>
    from . import ActionRecorder as ActionRecorder
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/ActionRecorder-master/ActionRecorder.py", line 8, in <module>
    import zipfile
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/zipfile.py", line 6, in <module>
    import binascii
ImportError: dlopen(/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so, 2): Library not loaded: libz.1.dylib
  Referenced from: /Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so
  Reason: unsafe use of relative rpath libz.1.dylib in /Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so with restricted binary
Traceback (most recent call last):
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'animation_nodes'
blender(4710,0x1252c9e00) malloc: can't allocate region
:*** mach_vm_map(size=18446744071685918720, flags: 100) failed (error code=3)
blender(4710,0x1252c9e00) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Rock Generator: Numpy not found.  Using Python's random.
Traceback (most recent call last):
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/flip_fluids_addon/__init__.py", line 55, in <module>
    from . import (
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/flip_fluids_addon/objects/__init__.py", line 35, in <module>
    from . import (
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/flip_fluids_addon/objects/flip_fluid_cache.py", line 29, in <module>
    from ..operators import draw_particles_operators
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/flip_fluids_addon/operators/__init__.py", line 41, in <module>
    from . import (
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/flip_fluids_addon/operators/preferences_operators.py", line 17, in <module>
    import bpy, os, shutil, json, zipfile, urllib.request, sys, textwrap
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/zipfile.py", line 6, in <module>
    import binascii
ImportError: dlopen(/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so, 2): Library not loaded: libz.1.dylib
  Referenced from: /Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so
  Reason: unsafe use of relative rpath libz.1.dylib in /Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so with restricted binary
blender(4710,0x1252c9e00) malloc: can't allocate region
:*** mach_vm_map(size=18446744071686025216, flags: 100) failed (error code=3)
blender(4710,0x1252c9e00) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Traceback (most recent call last):
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/MB-Lab-master/__init__.py", line 33, in <module>
    import numpy
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned

Traceback (most recent call last):
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/addons/blenderkit/__init__.py", line 70, in <module>
    from blenderkit import append_link
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/addons/blenderkit/append_link.py", line 20, in <module>
    from blenderkit import utils, ui
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/addons/blenderkit/utils.py", line 20, in <module>
    from blenderkit import paths, rerequests, image_utils
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/addons/blenderkit/paths.py", line 20, in <module>
    from blenderkit import tasks_queue, ui, utils
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/addons/blenderkit/ui.py", line 20, in <module>
    from blenderkit import paths, ratings, utils, search, upload, ui_bgl, download, bg_blender, colors, tasks_queue, \
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/addons/blenderkit/ratings.py", line 19, in <module>
    from blenderkit import paths, utils, rerequests, tasks_queue
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/addons/blenderkit/rerequests.py", line 20, in <module>
    from blenderkit import ui, utils, paths, tasks_queue, bkit_oauth
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/addons/blenderkit/bkit_oauth.py", line 20, in <module>
    from blenderkit import tasks_queue, utils, paths, search, categories, oauth, ui, ui_panels
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/addons/blenderkit/search.py", line 19, in <module>
    from blenderkit import paths, utils, categories, ui, colors, bkit_oauth, version_checker, tasks_queue, rerequests, \
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/addons/blenderkit/categories.py", line 22, in <module>
    import requests
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/urllib3/__init__.py", line 11, in <module>
    from . import exceptions
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/urllib3/exceptions.py", line 3, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/urllib3/packages/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/urllib3/packages/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/http/client.py", line 71, in <module>
    import email.parser
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/email/_policybase.py", line 7, in <module>
    from email import header
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/email/header.py", line 14, in <module>
    import binascii
ImportError: dlopen(/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so, 2): Library not loaded: libz.1.dylib
  Referenced from: /Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so
  Reason: unsafe use of relative rpath libz.1.dylib in /Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so with restricted binary
Traceback (most recent call last):
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/LilySurfaceScrapper/__init__.py", line 31, in <module>
    from . import frontend
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/LilySurfaceScrapper/frontend.py", line 9, in <module>
    from .CyclesMaterialData import CyclesMaterialData
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/LilySurfaceScrapper/CyclesMaterialData.py", line 9, in <module>
    from .MaterialData import MaterialData
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/LilySurfaceScrapper/MaterialData.py", line 24, in <module>
    from .ScrappersManager import ScrappersManager
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/LilySurfaceScrapper/ScrappersManager.py", line 26, in <module>
    from .Scrappers.AbstractScrapper import AbstractScrapper
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/LilySurfaceScrapper/Scrappers/AbstractScrapper.py", line 29, in <module>
    from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' (/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/LilySurfaceScrapper/site-packages/lxml/__init__.py)
Traceback (most recent call last):
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/screencastkeys/__init__.py", line 46, in <module>
    from . import utils
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/screencastkeys/utils/__init__.py", line 28, in <module>
    from . import addon_updator
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/screencastkeys/utils/addon_updator.py", line 24, in <module>
    import urllib.request
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/urllib/request.py", line 84, in <module>
    import base64
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/base64.py", line 11, in <module>
    import binascii
ImportError: dlopen(/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so, 2): Library not loaded: libz.1.dylib
  Referenced from: /Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so
  Reason: unsafe use of relative rpath libz.1.dylib in /Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so with restricted binary
blender(4710,0x1252c9e00) malloc: can't allocate region
:*** mach_vm_map(size=18446744071685963776, flags: 100) failed (error code=3)
blender(4710,0x1252c9e00) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Traceback (most recent call last):
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/__init__.py", line 68, in <module>
    from sverchok.core import sv_registration_utils, init_architecture, make_node_list
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/__init__.py", line 4, in <module>
    from sverchok.core.update_system import clear_system_cache
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/update_system.py", line 26, in <module>
    from sverchok import data_structure
  File "/Users/cd/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/data_structure.py", line 28, in <module>
    from numpy import (
  File "/Users/cd/Downloads/Blender 2.93 alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned

**Comment by 3DSinghVFX** [comment]
Did you try the build from the release page https://github.com/3DSinghVFX/animation_nodes/releases/tag/extranodes-cd-build

**Comment by luckychris** [comment]
yes, same result

**Comment by 3DSinghVFX** [comment]
> yes, same result

Okay.

**Comment by OmarEmaraDev** [comment]
This seems to be an issue with the MacOS Blender builds. This was reported in T85624 and T85648, and a fix was committed already I think. So try again with the daily builds in couple of days and it should work.

**Comment by luckychris** [comment]
ok, thank you, i will try that and let u know, whether it works

**Comment by luckychris** [comment]
still the same error in the build of today....i will try tomorrow again

**Comment by 3DSinghVFX** [comment]
> still the same error in the build of today....i will try tomorrow again

Okay.

**Comment by OmarEmaraDev** [comment]
@luckychris You should provide feedback in T85624 if you can.

**Comment by AlinaHanqq** [comment]
hi I install blender2.93 and download animation nodes for 2.93 but it does not work, please help me thanks!

s Python: Traceback(most recent call last)
Filbt'/Applications/Blender. app/Contents/Resources/2.93/scripts/startup/bl operators/userpref py", line 609, in execu
import zipfile
File "/Applications/Blender. app/Contents/Resources/2.93/python/lib/python39/zipfile. py", line 6, in <module>
import binascii
ImportError: dlopen(/Applications/Blender, app/Contents/Resources/2. 93/python/lib/python39/lib-dynload/binascii cpyt
Referenced from: /Applications/Blender. app/Contents/Resources/2. 93/python/lib/python.9/lib-dynload/binasci cpyth
Reason: unsafe use of relative rpath libz. 1. dylib in /Applications/ Blender. app/Contents/Resources/2.93/python/ib/pytl
location: <unknown location>: -1

**Comment by luckychris** [comment]
so i am happy, that i am not alone with this problem. ;)

**Comment by AlinaHanqq** [comment]
yes, i am also happy , I wish this problem can quickly solve so that we can use

**Comment by meikasahara** [comment]
There seems to be an additional/possibly related issue on the latest blender 2.93 build (d447bd3e4a9a) on linux; when activating animation nodes addon the following errors appear:
"
TypeError: PointerProperty(...) expected an RNA type, failed with: RuntimeError: , missing bl_rna attribute from 'RNAMetaPropGroup' instance (may not be registered)

Exception in module register(): /home/vdb/.config/blender/2.93/scripts/addons/animation_nodes/__init__.py
Traceback (most recent call last):
  File "/home/vdb/LOCAL/blender-2.93.0-d447bd3e4a9a-linux64/2.93/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/home/vdb/.config/blender/2.93/scripts/addons/animation_nodes/__init__.py", line 172, in register
    auto_load.register()
  File "/home/vdb/.config/blender/2.93/scripts/addons/animation_nodes/auto_load.py", line 28, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "an_PolygonIndicesSocket" registration error: display could not register
"

**Comment by 3DSinghVFX** [comment]
@meikasahara Hi. Did you try on the latest build of Blender 2.93?

**Comment by meikasahara** [comment]
@3DSinghVFX Yes, on build bfb2e87a9ea0 it displays a similar registration error (but with different sockets)
ValueError: bpy_struct "an_StructSocket" registration error: display could not register

**Comment by OmarEmaraDev** [comment]
The zlib error seem to be fixed in https://developer.blender.org/rB9fe53bd4a1ac0eaa63fcf1ebd151fe4db0411b49. Though builds are probably not updated yet.

@meikasahara I can replicate that. We will take a look.

**Comment by OmarEmaraDev** [comment]
@meikasahara Fixed upstream in https://github.com/JacquesLucke/animation_nodes/commit/20621d5a7f89b60d78a1187cf32f1d5bec8dc71b. Thanks for the report!

**Comment by 3DSinghVFX** [comment]
@OmarEmaraDev Thanks :)

**Comment by luckychris** [comment]
does this mean, if i try it with the master, it should now work? because i just tried...and still the same error...

**Comment by OmarEmaraDev** [comment]
@luckychris No. They haven't updated the builds yet. You should try again when they close https://developer.blender.org/T85648.

**Comment by luckychris** [comment]
ok, thank you

**Comment by luckychris** [comment]
ok, after a hard fight with pip/python/cython i now made it to compile animation nodes + extra nodes myself with python 3.9 and...could successfully install it in Blender. Thank for your help.

But...why don't you compile and provide this in here? You are the pro's and it should be just one more "automated" build for you, isn't it? Then more people could and would use your really helpful extra nodes. I do not think that every artist would like to install it manually and maybe even cannot do it.

**Comment by 3DSinghVFX** [comment]
> ok, after a hard fight with pip/python/cython i now made it to compile animation nodes + extra nodes myself with python 3.9 and...could successfully install it in Blender. Thank for your help.

That is good.

> But...why don't you compile and provide this in here? You are the pro's and it should be just one more "automated" build for you, isn't it? Then more people could and would use your really helpful extra nodes. I do not think that every artist would like to install it manually and maybe even cannot do it.

I have provided the [compiled build of AN+EN](https://github.com/3DSinghVFX/animation_nodes/releases/tag/extranodes-cd-build) for all OSs for Python 3.9.

**Comment by luckychris** [comment]
Sorry, then I was too blind and stupid to find that🤦🏻‍♂️

**Comment by 3DSinghVFX** [comment]
> Sorry, then I was too blind and stupid to find that🤦🏻‍♂️

Actually, the release page is bit hidden on GitHub. You can find all releases here https://github.com/3DSinghVFX/animation_nodes/releases
