### ISSUE TITLE
crash when inputting float list to marching squares threshold.

### ISSUE THREAD

**Issue by Yappu** [3DSinghVFX/animation_nodes#166]
Crashing on both 2.92 with python 3.7, and daily build 2.93 alpha with python 3.9, with their respective versions of AN+EN
When inputting the float list and adding a new input blender crashes instantly, or in some seconds later, when trying to reproduce.

Blender crash file here
[blender.crash.txt](https://github.com/3DSinghVFX/animation_nodes/files/6123949/blender.crash.txt)

**Comment by 3DSinghVFX** [comment]
@Yappu Hi. I have tested and it is working fine on my side. Can please attach the blend-file?

> When inputting the float list and adding a new input blender crashes instantly, or in some seconds later, when trying to reproduce.

BTW, what do you mean by *...adding a new input*?

**Comment by Yappu** [comment]
![billede](https://user-images.githubusercontent.com/23640092/110850206-cb804180-82af-11eb-82ba-02b7acbfcecd.png)

This setup, if i connect the integer list and press "new input" it crashes. changing the values in the other two inputs on the list to some other value before connecting it and it does not crash. if i turn off auto execution i can connect the node, but instant shutdown as soon as it executes.

here is the file, the create integer list is not connected, connect it and press new input.
[crash blend.zip](https://github.com/3DSinghVFX/animation_nodes/files/6125787/crash.blend.zip)

**Comment by Yappu** [comment]
if i scale the incoming cube in edit mode to get more geometry to project on, then input different values in the "create integer list" and connects it, it will crash when i change the "amplitude" of the "noise falloff" also.

**Comment by 3DSinghVFX** [comment]
@Yappu I can't reproduce this issue with your file. Btw, you should use *Float List* instead of *Integer List*.

Can you try the build from the [release page](https://github.com/3DSinghVFX/animation_nodes/releases/tag/extranodes-cd-build)?

![an_en_crash](https://user-images.githubusercontent.com/30294746/110943796-a3e9b180-8361-11eb-83e7-b2af9e9e4541.png)

**Comment by Gerstmann-Bradley** [comment]
I can reproduce the bug in 2.93 alpha, latest AN+EN.
Bug also presents with create float list.
Basically everything works fine, but I can not add a new input once already being connected.
Values in the socket don't help with the crash.
Execution method also doesn't help with the crash.

system: WIN 10.

**Comment by Yappu** [comment]
@3DSinghVFX i have tried builds from release page in 2.92, and from graphicall for 2.93. i will do a double check when i am home again.
Regarding use of integer list, i just followed along with Chris P's youtube video on the marching squares node to get a basic setup, have not tried with a float list, will also do that when i am back at my main computer.

**Comment by 3DSinghVFX** [comment]
> I can reproduce the bug in 2.93 alpha, latest AN+EN.
> Bug also presents with create float list.
> Basically everything works fine, but I can not add a new input once already being connected.
> Values in the socket don't help with the crash.
> Execution method also doesn't help with the crash.
> 
> system: WIN 10.

Thanks for feedback. Can you please run blender from *terminal*, and attach the screenshot of crash-error?

**Comment by Yappu** [comment]
@3DSinghVFX when using the float list, i dont crash instantly, but putting the float values close together (0.20, 0.23, 0.24) and then adjusting the frequency of the noise falloff, it crashes, this was in the version from the release page.

**Comment by Gerstmann-Bradley** [comment]
> > I can reproduce the bug in 2.93 alpha, latest AN+EN.
> > Bug also presents with create float list.
> > Basically everything works fine, but I can not add a new input once already being connected.
> > Values in the socket don't help with the crash.
> > Execution method also doesn't help with the crash.
> > system: WIN 10.
> 
> Thanks for feedback. Can you please run blender from _terminal_, and attach the screenshot of crash-error?

Sorry I am not sure how to do that. I have run blender using command line --debug-all if this is what you meant.
I can't upload file for some reasons, not possible to paste everything. I will just paste the last section before crash.
Not sure if this helps:

graph_id_tag_update: id=CUCurve flags=LEGACY_0 source=USER_EDIT
[SCScene :: View Layer]: Operation is entry point for update: PARAMETERS_ENTRY()
[SCScene :: View Layer]: Operation is entry point for update: GEOMETRY_EVAL()
[SCScene :: View Layer]: Operation is entry point for update: GEOMETRY_EVAL_DONE()
[SCScene :: View Layer]: Operation is entry point for update: GEOMETRY_SELECT_UPDATE()
[SCScene :: View Layer]: Operation is entry point for update: PARAMETERS_EXIT()
[SCScene :: View Layer]: Operation is entry point for update: COPY_ON_WRITE()
[SCScene :: View Layer]: Operation is entry point for update: PARAMETERS_EVAL()
[SCScene :: View Layer]: Accumulated recalc bits for OBTarget: 8322
[SCScene :: View Layer]: Accumulated recalc bits for CUCurve: 4286574467
[SCScene :: View Layer]: deg_evaluate_copy_on_write on CUCurve (0000023AFF41A678)
[SCScene :: View Layer]: deg_evaluate_copy_on_write on OBTarget (0000023AE258F3B8)
[SCScene :: View Layer]: BKE_curve_eval_geometry on CUCurve (0000023AFF41A678)
[SCScene :: View Layer]: BKE_object_data_select_update on CUCurve (0000023AFF41A678)
[SCScene :: View Layer]: BKE_object_eval_uber_data on OBTarget (0000023AE258F3B8)
[SCScene :: View Layer]: BKE_object_handle_data_update on OBTarget (0000023AE258F3B8)
[SCScene :: View Layer]: BKE_object_select_update on OBTarget (0000023AE258F3B8)
[SCScene :: View Layer]: BKE_object_data_select_update on CUCurve (0000023AFF41A678)
Depsgraph updated in 0.001865 seconds.
Depsgraph evaluation FPS: 0.187291
UI_menutype_draw: opening menu "TOPBAR_MT_editor_menus"
UI_menutype_draw: opening menu "NODE_MT_editor_menus"
UI_menutype_draw: opening menu "VIEW3D_MT_editor_menus"
UI_menutype_draw: opening menu "NODE_MT_editor_menus"

wm_event_do_handlers: Handling event
wmEvent  type:260 / WINDOW_DEACTIVATE, val:2 / RELEASE,
         prev_type:1 / LEFTMOUSE, prev_val:2 / RELEASE,
         shift:0, ctrl:0, alt:0, oskey:0, keymodifier:0, is_repeat:0,
         mouse:(561,1), ascii:' ', utf8:'', pointer:0000023AE3F138D8
UI_menutype_draw: opening menu "NODE_MT_editor_menus"

wm_event_do_handlers: Handling event
wmEvent  type:272 / TIMER, val:0 / NOTHING,
         prev_type:1 / LEFTMOUSE, prev_val:1 / PRESS,
         shift:0, ctrl:0, alt:0, oskey:0, keymodifier:0, is_repeat:0,
         mouse:(365,108), ascii:' ', utf8:'', pointer:0000023AE3F11858

wm_event_do_handlers: Handling event
wmEvent  type:1 / LEFTMOUSE, val:1 / PRESS,
         prev_type:1 / LEFTMOUSE, prev_val:2 / RELEASE,
         shift:0, ctrl:0, alt:0, oskey:0, keymodifier:0, is_repeat:0,
         mouse:(361,109), ascii:' ', utf8:'', pointer:0000023AE3F0F7D8

wm_event_do_handlers: Handling event
wmEvent  type:1 / LEFTMOUSE, val:2 / RELEASE,
         prev_type:1 / LEFTMOUSE, prev_val:1 / PRESS,
         shift:0, ctrl:0, alt:0, oskey:0, keymodifier:0, is_repeat:0,
         mouse:(361,109), ascii:' ', utf8:'', pointer:0000023AE3F100C8
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=TRANSFORM, GEOMETRY, PARAMETERS source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=TRANSFORM, GEOMETRY, PARAMETERS source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=TRANSFORM, GEOMETRY, PARAMETERS source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=TRANSFORM, GEOMETRY, PARAMETERS source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT
graph_id_tag_update: id=NTNodeTree flags=COPY_ON_WRITE source=USER_EDIT

**Comment by 3DSinghVFX** [comment]
@Yappu  @Gerstmann-Bradley  Can you please test the *Marching Triangles* node?

**Comment by Gerstmann-Bradley** [comment]
> @Yappu @Gerstmann-Bradley Can you please test the _Marching Triangles_ node?

I have just tried.
In the case of non-always execution and create float list.
The crash will occur when there is two 0, 0 in series.

Thus, there are several situation possible.
1. instantaneous crash upon linkage with threshold 0, 0.
2. if two values are non-0, crash after the second create input with 0.

**Comment by 3DSinghVFX** [comment]
> > @Yappu @Gerstmann-Bradley Can you please test the _Marching Triangles_ node?
> 
> I have just tried.
> In the case of non-always execution and create float list.
> The crash will occur when there is two 0, 0 in series.
> 
> Thus, there are several situation possible.
> 
>     1. instantaneous crash upon linkage with threshold 0, 0.
> 
>     2. if two values are non-0, crash after the second create input with 0.

Thanks for the feedback.

**Comment by Yappu** [comment]
@3DSinghVFX i am currently unable to test for at least 7-8 hours, do you need me to?

**Comment by 3DSinghVFX** [comment]
> @3DSinghVFX i am currently unable to test for at least 7-8 hours, do you need me to?

@Yappu It is Okay. 

BTW, I have just fixed the Marching Squares and Triangles nodes in commit https://github.com/3DSinghVFX/animation_nodes/commit/7da8dafa17029a1745ba1787891b55cd72a7dd1c

@Gerstmann-Bradley Can you please test these nodes?

**Comment by Yappu** [comment]
Oh very cool, i will check the patch when i get home! thank you

**Comment by Yappu** [comment]
it does not crash when inputting or adding with the list now, but turning up frequency and amplitude on the noise falloff still crashes it with the list input, this is in 2.93, i will test 2.92 after dinner

**Comment by Yappu** [comment]
here are the file i used and an error log from blender
[blender_debug_output.txt](https://github.com/3DSinghVFX/animation_nodes/files/6166349/blender_debug_output.txt)

[blendfile.zip](https://github.com/3DSinghVFX/animation_nodes/files/6166356/blendfile.zip)
